POST http://localhost:8080/api/auth/signin

{
  "email": "test@test.com",
"fullname": "perlinson",
"password": "123456",
}


###
POST http://localhost:8080/api/auth/login

{
  "email": "perlinson_2008@163.com",
"password": "123456",
}

###
GET  http://localhost:8080/api/room/
